tasks:
  default:
    onboard_world: WebChatbotOnboardWorld
    task_world: WebChatbotTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: worlds
overworld: WebChatOverworld
max_workers: 30
opt:
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_1Bdistill/model
      interactive_mode: True
      no_cuda: True
additional_args:
  page_id: 1 # Configure Your Own Page
